name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
        run: python main.py